rootProject.name = 'scm4j'

def moduleNames = [
        'scm4j-commons',
        'scm4j-deployer-api',
        'scm4j-deployer-engine',
        'scm4j-deployer-installers',
        'scm4j-installer',
        'scm4j-jenkins',
        'scm4j-releaser',
        'scm4j-releaser-gradle-plugin',
        'scm4j-vcs',
]

include(*moduleNames)
